---
- hosts: "{{host}}"
  gather_facts: false
  vars_files: vars/usuarios.yaml
  become: yes

  tasks:
    - name: Usuários criados
      debug:
        msg: "Usuarios {{ item.value.nome }} com senha {{ item.value.senha}} ."
      with_dict: "{{ usuarios }}"

    - name: Verifica e cria grupo sudo_ti caso nao exista
      group:
        name: sudo_ti
        state: present

    - name: Criar usuário {{ item.value.nome }}
      user:
        name: "{{ item.value.nome }}"
        state: present
        force: yes
        password: "{{ item.value.senha }}"
        shell: /bin/bash
        create_home: yes
        update_password: on_create
        append: yes
        groups: sudo_ti
      with_dict: "{{ usuarios }}"

    - name: Copiar arquivo do sudoers para grupo sudo_ti
      copy:
        src: files/sudo_ti
        dest: /etc/sudoers.d/sudo_ti
        owner: root
        group: root
        mode: 0644
