---
- hosts: "{{host}}"
  gather_facts: false
  become: yes

  tasks:
    - name: Verifica e cria grupo sudo_ti caso nao exista
      group:
        name: sudo_ti
        state: present

    - name: Criar usuário {{ usuario }}
      user:
        name: "{{ usuario }}"
        state: present
        force: yes
        password: "{{ senha | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        update_password: on_create
        append: yes
        groups: sudo_ti
      when:
        - usuario is defined
        - senha is defined

    - name: Copiar arquivo do sudoers para grupo sudo_ti
      copy:
        src: files/sudo_ti
        dest: /etc/sudoers.d/sudo_ti
        owner: root
        group: root
        mode: 0644
